const NAMESPACE = 'CHAT';

const ChatActionTypes = {
  SET_CURRENT_USERNAME: `${NAMESPACE}_SET_CURRENT_USERNAME`,
  SET_SIGN_IN_ERRORS: `${NAMESPACE}_SET_SIGN_IN_ERRORS`,
  RECEIVE_MESSAGE: `${NAMESPACE}_RECEIVE_MESSAGE`,
  GET_ACTIVE_USERS: `${NAMESPACE}_GET_ACTIVE_USERS`,
};

export { ChatActionTypes };
